### ISSUE TITLE
API Gateway error (504) on two different taxonid queries

### ISSUE THREAD

**Issue by skybristol** [iobis/obis-issues#132]
I ran into a "bad gateway" error on these two taxonids.

https://api.obis.org/statistics/all?taxonid=1070
https://api.obis.org/statistics/all?taxonid=794

They are valid in OBIS.

https://api.obis.org/taxon/1070
https://api.obis.org/taxon/794

**Comment by pieterprovoost** [comment]
Thanks, it seems like this happens for unaccepted taxa which do not have a valid taxon associated. I'll try to come up with a fix, although that will probably involve dropping all records linked to these taxa. See http://www.marinespecies.org/rest/AphiaRecordByAphiaID/794

**Comment by skybristol** [comment]
Per some of our earlier discussion this week over email, can you help me understand what "dropping all records linked to these taxa" would mean? Are you actually excluding records that fail some combination of QC tests from the live, end-of-pipeline index(es), or are you simply flagging them as dropped and excluding them from certain API responses?

I would strongly urge the latter approach with the added step, like @ekleins and I went back and forth on in email, of incorporating the QC information into the final record model.

In this case, I got "Turbellaria" from the API route you gave me earlier for all classes - https://api.obis.org/statistics/composition/class. How did it end up there?

**Comment by pieterprovoost** [comment]
@skybristol @diodon @wardappeltans Dropped means that these records are not included in API responses or statistics by default. As mentioned during earlier discussions these records are still entering the database and search index, which was not the case with the old system. However, records which are dropped because they do not have a match in WoRMS do not get assigned taxon identifiers, so they cannot be queried using a scientific name or taxon identifier (they can be retrieved by explicitly querying for dropped records and by filtering on depth or location for example). But maybe that needs to be revisited.

Records entering OBIS are now matched with WoRMS and get assigned the taxon identifiers (specied ID, genus ID, etc) of the accepted taxon. When using `scientificname` or `taxonid` in an API call, this name or ID first gets translated to an accepted ID, which is then used to query Elasticsearch. A search for `Scrobiculariidae` for example gets translated to `family_id = 1781` because `1781` is the taxon ID of the accepted taxon `Semelidae`. Records which are dropped for not having a WoRMS match do not have `species_id`, `genus_id`, etc and therefore cannot be retrieved by a taxonomic search. If we really need a way to retrieve these dropped records by taxonomy then I guess we need full text search on `scientificName` and other taxonomy related fields.

Regarding `Turbellaria`, as this is not an accepted taxon it should not show up in statistics. However, I expect that the fact that the Aphia record from the WoRMS API does not have a `valid_AphiaID` field (as is the case with synonyms) was erroneously interpreted as "this taxon is valid" by our software. But I need to review the code to be sure. In any case, as we do not have a valid alternative for this taxon, all records with scientific name Turbellaria will be dropped, hence my comment "will probably involve dropping all records linked to these taxa". Once that is fixed Turbellaria should no longer be in the statistics, and should be listed in the "no WoRMS match" list on relevant the dataset pages. Then, hopefully, the data providers will fix their datasets and assign another LSID to the affected records.
